name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # --- PARTIE 1 : INTEGRATION CONTINUE (CI) ---
  build:
    name: Build & Test Node
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Configurer Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installer les dependances
        run: npm install

      - name: Lancer le Lint (Verification du code)
        run: npm run lint --if-present

      - name: Lancer les tests
        run: npm test --if-present

      - name: Sauvegarder les fichiers
        uses: actions/upload-artifact@v4
        with:
          name: node-app-files
          path: .

  # --- PARTIE 2 : DEPLOIEMENT CONTINU (CD) ---
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    # Le déploiement ne se fait que sur un push sur master
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

  # --- PARTIE 3 : SÉCURITÉ (SCAN TRIVY) ---
  security:
    name: Scan Image Security (Trivy)
    runs-on: ubuntu-latest
    needs: docker # S'exécute après le job docker
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # On scanne l'image qui vient d'être envoyée sur le Docker Hub
          image-ref: '${{ secrets.DOCKER_USERNAME }}/node-app:latest'
          format: 'table'
          # Détection des vulnérabilités élevées et critiques uniquement
          severity: 'HIGH,CRITICAL'
          # Fait échouer le pipeline si des failles sont trouvées
          exit-code: '1'
